### ISSUE TITLE
still can't read my .ldb file

### ISSUE THREAD

**Issue by knownothingsnow** [anpsoft/LevelDbOneTab#3]
I'd like thank you for this solution first.It's like a burning candle to me in the darkness after I lost my oneTab data.But there is still some problem while I trying to practice.I managed to get old .ldb file in my backup and stuck after I ran you command.
<img width="1050" alt="screen shot 2018-12-05 at 21 43 34" src="https://user-images.githubusercontent.com/9696289/49517946-5ce5f980-f8d8-11e8-8ce9-95616877a9fa.png">
But this module is right in the same folder.BTW, the "11_29" folder is where I put files from leveldb folder.
<img width="506" alt="screen shot 2018-12-05 at 21 44 08" src="https://user-images.githubusercontent.com/9696289/49518018-8dc62e80-f8d8-11e8-8c04-e0223d5bd9b0.png">
So I am quite confusing about this.
Was I did something wrong? Please help me with this issues. Any info could be helpful!

**Comment by anpsoft** [comment]
Sorry for delay. 

I download it, place to desktop, unzip

1 - make dir for show folder
2 - try use not correct name for ldb files
3 - try use correct name to folder with copy of ldb files from leveldb folder in my Vivaldi (something like e:\Chrome User Data.!!!\User Data\Default\Local Storage\leveldb\ or  c:\Users\Andrey\AppData\Local\Vivaldi\User Data\Default\Local Storage\leveldb\)

this is correct result
![screen 2019-01-09_183044](https://user-images.githubusercontent.com/26188453/50913648-77fada80-143d-11e9-8c1f-3423b60e5be7.jpg)

you are sure what you have correct rights in system for desktop folder ?

**Comment by tiagodamian** [comment]
hi, i have seen your reply, i will try the solution  as soon as time allows it.

In my destop environment i do have the ryght read/write.

**Comment by knownothingsnow** [comment]
I still got the same error. I tried your solution both in cmd and PowerShell with administrator mode.I also tried rename my data folder into "leveldb". There were both failed.

**Comment by anpsoft** [comment]
you are sure what you use correct leveldb folder ?
may be you not store all files in buckup?
or chrome woring in this time and block files on disk


this is for example my folder

![image](https://user-images.githubusercontent.com/26188453/51428430-3bcd3400-1c0c-11e9-91d4-8267f9dd06f4.png)

also if you have all old folder, you may copy it to new chrome location 
and not  need any utilites :)
if not work,  you old folder is not correct of couse

chrome need close before any operations with chrome data folders

**Comment by anpsoft** [comment]
install latest Microsoft Visual C++ Redistributable 
this may help you

 https://support.microsoft.com/en-ph/help/2977003/the-latest-supported-visual-c-downloads

**Comment by knownothingsnow** [comment]
<img width="453" alt="Screen Shot 2019-03-26 at 17 41 04" src="https://user-images.githubusercontent.com/9696289/54986909-77aabe00-4fee-11e9-98ef-3f743910ee2a.png">
It doesn't work for me as before. I still want to thank you though. 
Data losing happen all the time and I am ready to move on.

**Comment by hybridview** [comment]
I had the same problem and this worked for me:

I copied all of the dll files from the location below into the BIN folder of my compiled LevelDBOneTab app. It then worked as expected. In your case, I think you would use the path of the version of Visual Studio that you used to build the app. In my case, I built using VS 20189, so took the redist files from that path. NOTE: I think these redist files are for when you build in Debug mode.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Redist\MSVC\14.21.27702\debug_nonredist\x86\Microsoft.VC142.DebugCRT

**Comment by anpsoft** [comment]
Yes
thanks

i want use virtual box for run clear windows, and test it
12 черв. 2019 18:14, "Andrew M" <notifications@github.com> напис.

**Comment by Ernart** [comment]
Hi I have the same problem too, 

Can you help me,

I have visual studio installed 2019 and put a copy of the 2 DLL from the folder exepath to the directory of C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Redist\MSVC\14.21.27702\debug_nonredist\x86\Microsoft.VC142.DebugCRT

Thanks


```

Microsoft Windows [Version 10.0.18363.959]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Ernart_PC> cd C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\onetabs

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\onetabs

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>cd C:\Windows\System32

C:\Windows\System32>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\onetabs

C:\Windows\System32>cd C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\onetabs

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>dir
 Volume in drive C has no label.
 Volume Serial Number is B8CB-4E69

 Directory of C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath

20/03/2019  06:41 PM    <DIR>          .
20/03/2019  06:41 PM    <DIR>          ..
20/03/2019  06:41 PM             7,680 LevelDbOneTab.exe
20/03/2019  06:41 PM         1,179,648 MyLevelDb.dll
20/03/2019  06:41 PM           662,528 Newtonsoft.Json.dll
               3 File(s)      1,849,856 bytes
               2 Dir(s)  470,683,332,608 bytes free

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>C:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb\
'C:\Users\Ernart_PC\Desktop\Onetab\New' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb\

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb\

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>cd
C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>cd
C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath

C:\Users\Ernart_PC\Desktop\Onetab\New folder\LevelDbOneTab-master\LevelDbOneTab-master\exepath>cd C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>dir
 Volume in drive C has no label.
 Volume Serial Number is B8CB-4E69

 Directory of C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath

23/07/2020  11:43 AM    <DIR>          .
23/07/2020  11:43 AM    <DIR>          ..
20/03/2019  06:41 PM             7,680 LevelDbOneTab.exe
20/03/2019  06:41 PM         1,179,648 MyLevelDb.dll
20/03/2019  06:41 PM           662,528 Newtonsoft.Json.dll
               3 File(s)      1,849,856 bytes
               2 Dir(s)  465,911,267,328 bytes free

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe C:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb\

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe c:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>LevelDbOneTab.exe c:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb\

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'MyLevelDb.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ConsoleApp1.Program.DbOpen(String path)
   at ConsoleApp1.Program.Main(String[] args)

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>dir
 Volume in drive C has no label.
 Volume Serial Number is B8CB-4E69

 Directory of C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath

23/07/2020  11:43 AM    <DIR>          .
23/07/2020  11:43 AM    <DIR>          ..
20/03/2019  06:41 PM             7,680 LevelDbOneTab.exe
20/03/2019  06:41 PM         1,179,648 MyLevelDb.dll
20/03/2019  06:41 PM           662,528 Newtonsoft.Json.dll
               3 File(s)      1,849,856 bytes
               2 Dir(s)  465,908,334,592 bytes free

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>DbOpen path: c:\Users\Ernart_PC\Desktop\Onetab\New folder\leveldb\
'DbOpen' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>Dbopen
'Dbopen' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Ernart_PC\Desktop\LevelDbOneTab-master\LevelDbOneTab-master\exepath>
```

**Comment by anpsoft** [comment]
Hello
i have big problems with health, so not work with computer last time
if you you have studio, you may re- build project, this may help with dlls

about out of index error, i not test it

you data in one tab is very big?

Andrey

**Comment by Ernart** [comment]
okay man get well soon and i hope everything would be better.  

not really just a couple of less than a hundred mb. 10k links?

I don't know I to rebuild stuff

will just go back the later month. 

thank you very much man

I just manually did that visual studio folder
